// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/sherise-variants/Authority.tsx": () => import("../components/mockups/sherise-variants/Authority.tsx"),
  "./components/mockups/sherise-variants/LifeJourney.tsx": () => import("../components/mockups/sherise-variants/LifeJourney.tsx"),
  "./components/mockups/sherise-variants/Manifesto.tsx": () => import("../components/mockups/sherise-variants/Manifesto.tsx"),
  "./components/mockups/sherise-variants/ModernStudio.tsx": () => import("../components/mockups/sherise-variants/ModernStudio.tsx"),
  "./components/mockups/sherise-lp-variants/ClinicalCase.tsx": () => import("../components/mockups/sherise-lp-variants/ClinicalCase.tsx"),
  "./components/mockups/sherise-lp-variants/LuxuryPractice.tsx": () => import("../components/mockups/sherise-lp-variants/LuxuryPractice.tsx"),
  "./components/mockups/sherise-lp-variants/PatientJourney.tsx": () => import("../components/mockups/sherise-lp-variants/PatientJourney.tsx"),
  "./components/mockups/sherise-lp-variants/SymptomMirror.tsx": () => import("../components/mockups/sherise-lp-variants/SymptomMirror.tsx")
};
