// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/sherise-variants/Authority.tsx": () => import("../components/mockups/sherise-variants/Authority.tsx"),
  "./components/mockups/sherise-variants/LifeJourney.tsx": () => import("../components/mockups/sherise-variants/LifeJourney.tsx"),
  "./components/mockups/sherise-variants/Manifesto.tsx": () => import("../components/mockups/sherise-variants/Manifesto.tsx"),
  "./components/mockups/sherise-variants/ModernStudio.tsx": () => import("../components/mockups/sherise-variants/ModernStudio.tsx")
};
